### ISSUE TITLE
Missing file find_close_nodes.m ?

### ISSUE THREAD

**Issue by ppop** [cvlab-epfl/balltracking#1]
I'm trying to run your code and I get the following error

> Undefined function or variable 'find_close_nodes'.
> 
> Error in add_interspace_edges_2 (line 83)
>                 pairs = find_close_nodes(x1, y1, z1, n1, x2, y2, z2, n2, [depth depth_z length(n1) length(n2)]);
> 
> Error in Create_tracking_graph (line 113)
>  add_interspace_edges_2(...
> 
> Error in main (line 38)
> Create_tracking_graph;

I think you're missing the definition in matlab of find_close_nodes.

**Comment by ppop** [comment]
Missing the predict as well?

> Undefined function or variable 'predict'.
> 
> Error in compute_edge_costs_2 (line 114)
>     [~,Pm_xz_out] = predict(MODEL.Class_m_xz, X_all);
> 
> Error in Create_tracking_graph (line 121)
> compute_edge_costs_2(POM, CONST.MIN_OCCUR, CONST.MAX_OCCUR, NoneSpace);
> 
> Error in main (line 38)
> Create_tracking_graph;

**Comment by maksay** [comment]
@ppop , thank you for the feedback. For the first function,  find_close_nodes, it was indeed an error. I forgot to compile the appropriate mex file. I have updated the code in Compile_and_setup.

For the second function, I think you need Matlab Statistics and ML toolbox. The predict function
is a standard function from it. In our particular case we use the TreeBagger model (ensemble of decision trees) which is either learned or loaded from models/ folder and used to classify the states.

**Comment by ppop** [comment]
thanks! that works well (besides some issues I'm having with gurobi licensing).
